spring.sendgrid.api-key: <sendgridkey>
spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true